services:
  spark-master:
    image: jupyter/all-spark-notebook:42f4c82a07ff
    container_name: spark-master
    hostname: spark-master
    networks:
      - spark-net
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - PYSPARK_PYTHON=/opt/conda/bin/python
      - PYSPARK_DRIVER_PYTHON=/opt/conda/bin/python
    volumes:
      - ./nbs:/home/jovyan/work/nbs:ro
    command:  bash -c "exec $$SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --webui-port 8080 --port 7077"

  spark-worker-1:
    image: jupyter/all-spark-notebook:42f4c82a07ff
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    networks:
      - spark-net
    ports:
      - "8081:8081"
    environment:
      - PYSPARK_PYTHON=/opt/conda/bin/python
      - PYSPARK_DRIVER_PYTHON=/opt/conda/bin/python
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    volumes:
      - ./nbs:/home/jovyan/work/nbs:ro
    command: bash -c "exec $$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker --host spark-worker-1 --webui-port 8081 --work-dir /tmp/spark-work spark://spark-master:7077"

  spark-worker-2:
    image: jupyter/all-spark-notebook:42f4c82a07ff
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    networks:
      - spark-net
    ports:
      - "8082:8081"
    environment:
      - PYSPARK_PYTHON=/opt/conda/bin/python
      - PYSPARK_DRIVER_PYTHON=/opt/conda/bin/python
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    volumes:
      - ./nbs:/home/jovyan/work/nbs:ro
    command: bash -c "exec $$SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker --host spark-worker-2 --webui-port 8081 --work-dir /tmp/spark-work spark://spark-master:7077"

  jupyter-notebook:
    image: jupyter/all-spark-notebook:42f4c82a07ff
    container_name: jupyternb
    hostname: jupyternb
    depends_on:
      - spark-master
    networks:
      - spark-net
    user: root
    ports:
      - "8888:8888"
    environment:
      - PYSPARK_PYTHON=/opt/conda/bin/python
      - PYSPARK_DRIVER_PYTHON=/opt/conda/bin/python
    volumes:
      - ./nbs:/home/jovyan/work/nbs
      - ./events:/tmp/spark-events
    command: bash -c "pip install gdown faiss-cpu && gdown -O /home/jovyan/work/nbs/un-general-debates.csv 1p2FqqFP-ZbmhFdOmvZoQzdDyF5D0MRDn; start-notebook.sh --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
    
networks:
    spark-net:
        driver: bridge
